Args = --initialize-at-build-time=org.leargon.backend.model,\
       groovy.lang,\
       org.codehaus.groovy,\
       org.apache.groovy,\
       java.beans,\
       com.sun.beans,\
       groovyjarjarantlr4,\
       net.bytebuddy \
       org.hibernate.bytecode.internal.bytebuddy.BytecodeProviderImpl \
       --initialize-at-run-time=org.leargon.backend.domain \
       --report-unsupported-elements-at-runtime \
       -Dhibernate.bytecode.provider=none
